# Generated by Django 3.2.3 on 2021-05-21 11:43

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                # ('post_img', models.ImageField(default='post_pic.jpg', upload_to=blog.models.post_img_path)),
                ('post_title', models.CharField(max_length=250)),
                ('post_detail', models.TextField(max_length=1000)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_like', models.ManyToManyField(
                    blank=True, related_name='_blog_post_post_like_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_detail', models.TextField(max_length=150)),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('comment_author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
